### ISSUE TITLE
Doesn't format since latest update

### ISSUE THREAD

**Issue by Larsklopstra** [shufo/vscode-blade-formatter#133]
Doesn't format code since latest update.

## Context (Environment)

macOS 11.4, Apple M1. Visual Studio Code version May 2021 (version 1.57).

## Description

Nothing happens on format. Tried to reinstall the extension but that doesn't work either. The only way to use this extension is by downgrading to April 2021 (version 1.56).

**Comment by v360-tech** [comment]
## Context 
Ubuntu 20.04 LTS, VS Code (1.57)

## Description
Same as above.

**Comment by suendri** [comment]
Same as above

**Comment by suendri** [comment]
Windows 10 64Bit, Vs Code 1.57.0 Same as above

**Comment by Larsklopstra** [comment]
Seems to be fixed now, I'll keep this issue open until it has been confirmed as being fixed

**Comment by shufo** [comment]
Hi @Larsklopstra 
Thank you for reporting the issue!
This behaviour is now fixed above https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.7.15

Since VSCode 1.57 introduced breaking change in vscode-oniguruma so this extension could not work on VSCode 1.57.
related issue: https://github.com/shufo/vscode-blade-formatter/issues/137
