### ISSUE TITLE
Comments keep getting indented on every save or manual format trigger

### ISSUE THREAD

**Issue by JonathanATyler** [shufo/vscode-blade-formatter#22]
## Context (Environment)
OS: Windows 10
VSCode: 1.51.1
V-B-F: 0.6.1

## Description
Every time I save, paste or manually apply formatting any comments are indented over and over beyond the 4-space setting.
Changing the "Wrap Attributes" setting does not have an effect.

Comments should only be indented once at the given space/tab setting.

**Comment by yCodeTech** [comment]
This needs to be reopened and fixed! For me, this only happens when there's only a comment and nothing else inside @php tags.

Starts off as this:

    @php
	    /**
	     * Counterparts:
	     * - resources/assest/styles/components/_forms.scss
	     * - resources/assest/scripts/routes/templateContact.js
	     * - app/ajax.php
	     */
    @endphp

And ends up like this after 4 saves/formats

    @php
	    /**
					 * Counterparts:
					 * - resources/assest/styles/components/_forms.scss
					 * - resources/assest/scripts/routes/templateContact.js
					 * - app/ajax.php
					 */
    @endphp

While using the php tags instead of the blade directive, it fixes the problem, but the start of the multiline block loses its indentation.

So the expected outcome:

    <?php
	    /**
	     * Counterparts:
	     * - resources/assest/styles/components/_forms.scss
	     * - resources/assest/scripts/routes/templateContact.js
	     * - app/ajax.php
	     */
    ?>
Become this:

    <?php
	    /**
	             * Counterparts:
	             * - resources/assest/styles/components/_forms.scss
	             * - resources/assest/scripts/routes/templateContact.js
	             * - app/ajax.php
	             */
    ?>
