### ISSUE TITLE
use '$' in blade will get formatting error

### ISSUE THREAD

**Issue by loneight** [shufo/vscode-blade-formatter#398]
## Template
- Example 1:
```
@php
　if($a){
　　$a = '$';
　}
@endphp
```

- Example 2:

```
@foreach ($a as $b)
'$'
@endforeach

@if($a as $b)
'$'
@endif
```

## Context (Environment)

Laravel: 8.x
PHP: 7.x

## Description

- After format exmaple 1 
it will get error:
```
Parse Error : syntax error, expecting '}' on line
```

- After format exmaple 2 
it will disappear and only leave ' in blade.
```
@foreach ($a as $b)
'@endforeach

@if
'@endif
```
they will work fine when i change '$' to "$".

**Comment by shufo** [comment]
Thanks @loneight 

- Example1
It seems if unicode char code U+3000 is included in the Template, the error will occur.

![image](https://user-images.githubusercontent.com/1641039/167748536-4e470fdc-7661-4835-b8ef-14d5088f7b67.png)

Please make sure ASCII space or Tab is used.

- Example2

Maybe this is a different issue, but I just tried it and didn't have the same problem, so it may be fixed in the latest version. Please give it a try.

**Comment by loneight** [comment]
thank you, they work fine
