### ISSUE TITLE
Option to disable wrapping chained method inside @php

### ISSUE THREAD

**Issue by jihad28** [shufo/vscode-blade-formatter#571]
Hi
I have looked to disable wrapping inside `@php` but could not find anything I have only found `Wrap Attributes` but this is for HTML and does not affect code inside `@php`.

Example
I want to preserve the code like this
```blade
@php
    $timezone = config('business.timezone');
    $date = now($timezone)->subDays(10)->toDateString();
@endphp
```
But it will be changed to this if it's more than 2 methods
```blade
@php
    $timezone = config('business.timezone');
    $date = now($timezone)
        ->subDays(10)
        ->toDateString();
@endphp
```

It will be cool if there is another option for this like wrap it if longer than N characters or an option to disable it.

**Comment by MinSulaiman** [comment]
**PSR standard should be adhered to anyway**, and some general readability good practices; like each method chaining being on a separate line.

In my opinion - that no one asked for - people should learn how to cope with standardized practices, instead of forcing others to their lint code after them.

**Comment by jihad28** [comment]
@MinSulaiman 
Yeah, I'm with you on that but sometimes when writing code, you want a one liner as it's easier to read.
For example,
This
```blade
@php
    $tz = config('business.timezone');
    $range = now($tz)->subMonths(1)->toDateString() .' | ' . now($tz)->toDateString();
@endphp
```
Will become this
```blade
@php
    $tz = config('business.timezone');
    $range =
        now($tz)
            ->subMonths(1)
            ->toDateString() .
        ' | ' .
        now($tz)->toDateString();
@endphp
```
So, an option for wrapping methods would be good or at least an option to disable wrapping or improving the formatting when joined with a string.
We have `Wrap Attributes` so why not a `Warp Chained Methods` 😃

**Comment by MinSulaiman** [comment]
Yeah, that's an interesting, practical use-case. May I suggest, @shufo , that if we wrap it with parenthesis, it would ignore the chaining too, instead of ignoring and removing them?!

```blade
@php
$tz = config('business.timezone');
$range = (now($tz)->subMonths(1)->toDateString() . ' | ' . now($tz)->toDateString());
@endphp
```

**Comment by shufo** [comment]
@jihad28 @MinSulayman Thanks for suggesting the featuere!
The behavior of this chained methods is due to [prettier/plugin-php](https://github.com/prettier/plugin-php) and has nothing to do with this extension, so I think it is a good idea to work around it with this extension's own options. 
Related issue: https://github.com/prettier/plugin-php/issues/607

The problem is that this extension relies heavily on prettier/plugin-php for php formatting, so implementation may be a bit tricky :sweat_smile: 

Or maybe we can send a PR to prettier/plugin-php to add an option to disable the formatting of the chained method.

I'll consider it anyway. Thank you.
